// SPDX-License-Identifier: Apache-2.0
/**
 * D15 · `synth/guard-not-self-defeating` — and D21, `quality/capture-ratio-band`,
 * which is the same lesson at two scales: a measurement contaminated by the
 * thing it was supposed to measure.
 *
 * ── D15, THE DEFECT ────────────────────────────────────────────────────────
 * The anti-empty-stub guard stripped headings and known placeholders and
 * required ≥120 characters of residual prose. Its strip list did not remove
 * `## Related` wikilink lines — so **six machine-generated cross-links
 * (~144 chars) carried otherwise-empty pages over the floor.** 57 empty pages
 * were laundered into `status: active` and indexed as real knowledge.
 *
 * It hid because the guard reported it was working. Its own measurement was
 * contaminated by a LATER pipeline stage's output, which nobody thought of as
 * content.
 *
 * ── D21, THE DEFECT ────────────────────────────────────────────────────────
 * The freshness rubric banded 520 of 595 pages "healthy". `Band` was — to
 * within five pages — **a restatement of `synthesis_mode == hosted`**. It
 * measured whether an LLM ran, and nothing else. 164 of those "healthy" pages
 * had been clipped to 6,000 characters; 56 came from sources over 25,000.
 *
 * It hid because it produced a number that went UP when the pipeline ran, which
 * is exactly what a health metric is supposed to do.
 */

import { test } from "node:test";
import assert from "node:assert/strict";
import { proseWords, assessQuality, blindSpots } from "./capture-ratio.js";

/** N words of real prose. */
const prose = (n: number): string =>
  Array.from({ length: n }, (_, i) => `sentence${i}`).join(" ");

// ─────────────────────────────────────────────────────────────────────────────
// D15 · the guard that its own pipeline defeated
// ─────────────────────────────────────────────────────────────────────────────

test("D15 · SIX MACHINE CROSS-LINKS DO NOT CARRY AN EMPTY PAGE — the literal defect", () => {
  // The upstream page, reconstructed: a heading, a banner, and a `## Related`
  // block of six wikilinks. ~144 characters of "prose" by the old guard's count.
  const page = [
    "# Kubernetes Networking",
    "",
    "> _Synthesis pending._",
    "",
    "## Related",
    "",
    "- [[Container Runtime Interface]]",
    "- [[Service Mesh Basics]]",
    "- [[Ingress Controllers]]",
    "- [[CNI Plugins]]",
    "- [[Network Policies]]",
    "- [[Load Balancing Patterns]]",
    "",
  ].join("\n");

  assert.ok(page.length > 200, "the fixture must be long enough to have fooled a character-count floor");
  assert.equal(
    proseWords(page),
    0,
    "MACHINE-GENERATED CROSS-LINKS COUNTED AS PROSE — this is D15, and it laundered 57 empty pages " +
    "into `status: active`",
  );

  const q = assessQuality(page, 48_000);
  assert.equal(q.band, "empty", "the page was banded as anything other than empty");
});

test("D15 · a raw character count WOULD have passed it — the defect is real", () => {
  // Plant the old guard and watch it fail. Without this, the assertion above
  // could be passing because the fixture is trivially short.
  const page = [
    "# Kubernetes Networking", "", "## Related", "",
    "- [[Container Runtime Interface]]", "- [[Service Mesh Basics]]", "- [[Ingress Controllers]]",
    "- [[CNI Plugins]]", "- [[Network Policies]]", "- [[Load Balancing Patterns]]",
  ].join("\n");

  const oldGuardResidual = page.replace(/^#{1,6}\s.*$/gm, "").replace(/\s+/g, " ").trim();
  assert.ok(
    oldGuardResidual.length >= 120,
    `the old guard's floor was 120 chars and this fixture leaves ${oldGuardResidual.length} — ` +
    `it must exceed the floor, or this test proves nothing`,
  );
  assert.equal(proseWords(page), 0, "the shipped guard must reach the opposite conclusion");
});

test("D15 · every machine-writable line shape is stripped", () => {
  // A strip list is only as good as its coverage, and D15 was one missing shape.
  // Each of these is something a pipeline stage — not a human — emits.
  const cases: Array<[string, string]> = [
    ["heading", "# Title\n## Section\n### Sub"],
    ["frontmatter", "---\ntitle: x\nsensitivity: private\n---\n"],
    ["fenced code", "```js\nconst x = 1;\nconsole.log(x);\n```"],
    ["tilde fence", "~~~\nraw block\n~~~"],
    ["html comment", "<!-- generated by auto-compile -->"],
    ["horizontal rule", "---\n***\n___"],
    ["block quote banner", "> _Synthesis pending._\n> Generated automatically."],
    ["italic placeholder", "_No content yet._"],
    ["table row", "| a | b |\n| - | - |"],
    ["bare wikilinks", "[[One]] [[Two]] [[Three]]"],
    ["list of wikilinks", "- [[One]]\n* [[Two]]\n+ [[Three]]"],
    ["list of md links", "- [One](a.md)\n- [Two](b.md)"],
    ["bare urls", "https://example.com/a https://example.com/b"],
    ["placeholders", "TBD\nTODO\nN/A\nnone\nplaceholder\n—"],
  ];

  for (const [name, text] of cases) {
    assert.equal(proseWords(text), 0, `${name} counted as prose`);
  }
});

test("D15 · REAL PROSE STILL COUNTS — the guard is not self-defeating in the other direction", () => {
  // The counter-test. A strip list that removes everything would pass every
  // assertion above and reject every real page, and the fix would be reverted
  // within a week.
  const page = [
    "# Kubernetes Networking",
    "",
    "The CNI plugin assigns each pod an IP from the cluster CIDR, and kube-proxy programs",
    "the node's dataplane so that traffic to a Service VIP is load balanced across the",
    "endpoints backing it. On most clusters this is iptables or IPVS today, and eBPF where",
    "Cilium is installed.",
    "",
    "## Related",
    "- [[Service Mesh Basics]]",
  ].join("\n");

  assert.ok(proseWords(page) > 40, "real prose was stripped along with the machine output");
});

test("D15 · a mixed line — prose CONTAINING a wikilink — is prose", () => {
  // Only a line that is ONLY links is machine output. Getting this wrong would
  // silently discard the most densely linked (and usually best) human pages.
  const line = "The scheduler consults [[Node Affinity]] before binding a pod to a node.";
  assert.ok(proseWords(line) >= 10, "a prose line containing a wikilink was stripped entirely");
});

test("D15 · the strip list does not depend on a LATER stage's output", () => {
  // The root cause, asserted directly: adding cross-links must not change the
  // verdict. Upstream, running one more pipeline stage flipped 57 pages from
  // "empty" to "active" without adding a word of knowledge.
  const bare = "# Title\n\n> _pending_\n";
  const afterCrossLinker = bare + "\n## Related\n" +
    Array.from({ length: 12 }, (_, i) => `- [[Generated Link ${i}]]`).join("\n") + "\n";

  assert.equal(
    proseWords(bare),
    proseWords(afterCrossLinker),
    "RUNNING A LATER PIPELINE STAGE CHANGED THE GUARD'S MEASUREMENT — that is D15 exactly",
  );
});

// ─────────────────────────────────────────────────────────────────────────────
// D21 · a band that measures the pipeline instead of the page
// ─────────────────────────────────────────────────────────────────────────────

test("D21 · A CLIPPED PAGE FROM A LARGE SOURCE IS `thin` — the 164 pages", () => {
  // The upstream signature: fluent, long enough, LLM-generated, and written from
  // 6,000 of 48,000 characters. The old rubric called it healthy.
  const q = assessQuality(prose(600), 48_000);
  assert.equal(q.band, "thin", "a page reflecting 7.5% of its source was not flagged");
  assert.match(q.reason, /TRUNCATION SIGNATURE/);
  assert.match(q.reason, /Re-synthesise from the full source/, "the band must say what to do about it");
});

test("D21 · the band is NOT a restatement of 'an LLM ran'", () => {
  // The defect stated as a property. Two pages, both LLM-written, both fluent,
  // identical in every way the old rubric could see — and they must band
  // differently, because one saw its source and one did not.
  const clipped = assessQuality(prose(600), 48_000);
  const complete = assessQuality(prose(600), 9_000);

  assert.notEqual(
    clipped.band,
    complete.band,
    "two pages identical except for how much of their source they saw got the same band — the " +
    "metric is measuring the pipeline, not the page",
  );
  assert.equal(complete.band, "healthy");
});

test("D21 · the corpus median of 4% at ≥5,000-word sources is VISIBLE from this metric", () => {
  // The number the upstream system could not see with any metric it had.
  const q = assessQuality(prose(200), 30_000);
  assert.ok(q.capture_ratio !== null);
  assert.ok(q.capture_ratio! < 0.05, `ratio ${q.capture_ratio} — the 4% corpus is not visible`);
  assert.equal(q.band, "thin");
});

test("D21 · UNMEASURABLE IS A THIRD ANSWER — not healthy, not thin", () => {
  // Collapsing "I cannot measure this" into either neighbour is precisely what
  // the old rubric did. An unmeasurable page is exactly where a truncated one
  // hides, so it must be neither a pass nor an accusation.
  const q = assessQuality(prose(600), null);
  assert.equal(q.band, "unmeasurable");
  assert.equal(q.capture_ratio, null, "an unknown source size produced a numeric ratio");
  assert.match(q.reason, /This is NOT a pass/);

  assert.equal(assessQuality(prose(600), 0).band, "unmeasurable", "a zero source size must not divide");
});

test("D21 · the bands are ORDERED and reachable — a rubric nothing can top is not a rubric", () => {
  // Nothing in the upstream corpus could score above 87 out of 100, so the
  // rubric could not separate good from adequate. Every band here must be
  // reachable from a plausible page.
  assert.equal(assessQuality("", 10_000).band, "empty");
  assert.equal(assessQuality(prose(50), 10_000).band, "thin");
  assert.equal(assessQuality(prose(400), 10_000).band, "adequate");
  assert.equal(assessQuality(prose(700), 10_000).band, "healthy");
  assert.equal(assessQuality(prose(400), null).band, "unmeasurable");
});

test("D21 · a SHORT page from a SHORT source is not accused", () => {
  // I4's counter-case. A 60-word note about a 400-char source is complete, and a
  // metric that calls it thin trains people to ignore the metric.
  const q = assessQuality(prose(60), 400);
  assert.notEqual(q.band, "thin", "a complete short page was flagged as truncated");
  assert.equal(q.band, "healthy");
});

test("D21 · the word FLOOR only applies against a substantial source", () => {
  const q = assessQuality(prose(100), 900);
  assert.notEqual(q.band, "thin", "the 250-word floor fired against a 900-char source");
});

test("D21 · EVERY assessment ships its BLIND SPOTS", () => {
  // The rubric this replaces was trusted because nobody could see what it was
  // blind to. Publishing a metric without its blind spots is how that happens.
  for (const q of [
    assessQuality(prose(600), 48_000),
    assessQuality(prose(600), 9_000),
    assessQuality("", 100),
    assessQuality(prose(600), null),
  ]) {
    assert.ok(q.blind_spots.length >= 4, `band ${q.band} shipped without its blind spots`);
  }

  const spots = blindSpots().join(" ");
  assert.match(spots, /never a target/, "the anti-Goodhart caveat is missing");
  assert.match(spots, /complete and WRONG/, "the metric must disclaim factual accuracy");
  assert.match(spots, /sutra eval/, "it must point at what DOES measure quality");
});

test("D21 · the ratio is a FLOOR, not a target — a padded page is not the metric's job", () => {
  // Stated as a test so nobody optimises against it later: this metric will
  // reward restatement, and that is a known, published limitation rather than a
  // bug to fix by tightening the number.
  const padded = assessQuality((prose(20) + " ").repeat(30), 5_000);
  assert.equal(padded.band, "healthy");
  assert.ok(
    padded.blind_spots.some((s) => /padded with restatement/.test(s)),
    "the blind spot that explains this exact result is not published with it",
  );
});

// ─────────────────────────────────────────────────────────────────────────────
// Where D15 and D21 meet
// ─────────────────────────────────────────────────────────────────────────────

test("D15+D21 · a cross-linked EMPTY page is `empty`, not `healthy`", () => {
  // Both defects in one artifact — and this combination is what put 57 pages
  // into the index as knowledge. The D15 guard says there is no prose; the D21
  // band must not then rescue it on a ratio computed from links.
  const page = "# Title\n\n## Related\n" +
    Array.from({ length: 8 }, (_, i) => `- [[Link ${i}]]`).join("\n");

  const q = assessQuality(page, 200);   // a tiny source, so the ratio alone would look fine
  assert.equal(q.band, "empty", "an empty page was rescued by a favourable capture ratio");
  assert.match(q.reason, /D15/, "the reason must cite why cross-links do not count");
});
