#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
/**
 * THE LAYOUTS. Hand-placed coordinates — the part of a diagram that needs
 * judgement. The shell, palette and legend come from `build-diagrams.mjs`, so
 * the six views cannot drift apart visually.
 *
 * Spacing rules, enforced by eye and checked by `check-diagrams.mjs`:
 *   - box height 60 (80–120 for a big block)
 *   - ≥40px vertical gap between stacked boxes; connectors live IN the gap
 *   - the legend sits OUTSIDE every boundary, and the viewBox fits it
 *
 *   node scripts/diagrams.mjs
 */

import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { box, group, arrow, legend, card, SHELL, OUT } from "./build-diagrams.mjs";

const built = [];
function emit(d) {
  writeFileSync(join(OUT, `${d.slug}.html`), SHELL(d), "utf8");
  built.push(d);
  console.log(`  ${d.slug}.html`);
}

const FOOT = (n) =>
  `Sutra · ${n} · generated by scripts/diagrams.mjs · hand-laid inline SVG, no render step · renders offline`;

// ═════════════════════════════════════════════════════════════════════════════
// 1 · THE GATE — the four enforcement points. The most important view.
// ═════════════════════════════════════════════════════════════════════════════
emit({
  slug: "gate",
  accent: "gate",
  title: "Sutra — The Gate",
  h1: "The Gate — four independent enforcement points",
  subtitle:
    "Every read path in the product passes all four. They are deliberately redundant: <strong>each one has failed " +
    "independently in the system Sutra was extracted from, and the other three held.</strong> The ceiling is read from " +
    "the environment at server startup and is never accepted as a tool argument — a model can ask for anything, and " +
    "cannot change what it is allowed to see.",
  viewBox: "0 0 1180 700",
  body: [
    group(30, 30, 250, 400, "authored", "THE VAULT — plain markdown, git"),
    box(55, 70, 200, 60, "authored", "public note", "sensitivity: public"),
    box(55, 170, 200, 60, "authored", "private note", "sensitivity: private"),
    box(55, 270, 200, 60, "gate", "secret note", "sensitivity: secret", "credentials · health · finance"),
    box(55, 350, 200, 55, "gate", "do_not_learn", "orthogonal to tier"),

    group(330, 30, 480, 490, "gate", "THE FOUR ENFORCEMENT POINTS"),
    box(360, 70, 420, 70, "gate", "1 · classify at ingest", "gate/patterns.ts + Classify.ps1 — one shared rule set", "floors BEFORE anything downstream can read it"),
    box(360, 180, 420, 70, "gate", "2 · Brain.visible()", "the corpus walk — every read path goes through it", "local_only is never lifted, by any promotion"),
    box(360, 290, 420, 70, "gate", "3 · sensitivityGuard()", "rank(source) <= rank(destination) — ~120 lines", "the comparison, and nothing else"),
    box(360, 400, 420, 70, "gate", "4 · MCP per-tool ceiling", "read from the environment AT STARTUP", "no tool takes a tier, scope or override"),

    group(860, 30, 290, 300, "serve", "DESTINATIONS"),
    box(885, 70, 240, 60, "serve", "hosted model", "accepts PUBLIC only"),
    box(885, 170, 240, 60, "serve", "local model", "accepts every tier — nothing leaves"),
    box(885, 260, 240, 55, "serve", "your terminal", "direct render, no model in the loop"),

    arrow(255, 100, 360, 100, "authored", false, "public"),
    arrow(255, 200, 360, 205, "authored", false, "private"),
    arrow(255, 300, 360, 320, "gate", false, "secret"),

    arrow(780, 105, 885, 100, "serve", false, "allowed"),
    arrow(780, 320, 885, 195, "serve", true, "local only"),

    // The refusal. Rose, dashed, and labelled — the most important edge here.
    `<line x1="780" y1="430" x2="880" y2="180" stroke="#fb7185" stroke-width="2" stroke-dasharray="6,4" opacity="0.9"/>`,
    `<circle cx="830" cy="305" r="15" fill="#020617" stroke="#fb7185" stroke-width="2"/>`,
    `<text x="830" y="311" fill="#fb7185" font-size="15" font-weight="700" text-anchor="middle">×</text>`,
    `<text x="830" y="345" fill="#fb7185" font-size="9" font-weight="600" text-anchor="middle">REFUSED</text>`,

    `<rect x="360" y="500" width="790" height="70" rx="8" fill="#0f172a"/>`,
    `<rect x="360" y="500" width="790" height="70" rx="8" fill="rgba(136,19,55,0.25)" stroke="#fb7185" stroke-width="1.5"/>`,
    `<text x="755" y="524" fill="#fb7185" font-size="11" font-weight="700" text-anchor="middle">THE SECRET FLOOR IS ABSOLUTE</text>`,
    `<text x="755" y="543" fill="#e2e8f0" font-size="9.5" text-anchor="middle">local_only content never reaches any LLM — hosted or local-via-a-harness.</text>`,
    `<text x="755" y="558" fill="#94a3b8" font-size="9.5" text-anchor="middle">Not under an override. Not under a flag. Not for convenience. Not for an administrator.</text>`,

    `<text x="35" y="470" fill="#64748b" font-size="9" font-weight="600">WHAT THE CALLER LEARNS</text>`,
    `<text x="35" y="488" fill="#94a3b8" font-size="9">the COUNT of what was withheld,</text>`,
    `<text x="35" y="502" fill="#94a3b8" font-size="9">by tier — never the content.</text>`,
    `<text x="35" y="522" fill="#34d399" font-size="9">Visible: 812</text>`,
    `<text x="35" y="536" fill="#fb7185" font-size="9">Withheld: private 401,</text>`,
    `<text x="35" y="550" fill="#fb7185" font-size="9">secret 37, do_not_learn 12</text>`,

    legend(30, 620, ["authored", "gate", "serve"]),
  ].join("\n      "),
  cards: [
    card("rose", "Why four, and not one", [
      "Defence in depth is not redundancy here.",
      "<strong>Each of the four has failed independently</strong> in the upstream system's history — a dead path-floor band, an unmatched key shape, a stale index, a config a harness stopped reading.",
      "Each time, the other three held.",
    ]),
    card("rose", "What cannot lift the floor", [
      "A promotion — <code>Brain.visible()</code> only consults them for <code>private</code>.",
      "An override — the MCP path passes <code>allowSecret: false</code>, unconditionally.",
      "A ceiling — <code>local_only</code> fails the guard at every ceiling but its own.",
      "An Enterprise role — the floor is checked <em>before</em> clearance is read.",
    ]),
    card("emerald", "The trust demo", [
      "<code>sutra gate</code> reports the ceiling, what is visible, and what is withheld by tier.",
      "It computes those counts with <strong>the same <code>visible()</code></strong> the real read paths use — not a separate summary that could drift from them.",
    ]),
  ],
  footer: FOOT("the gate"),
});

// ═════════════════════════════════════════════════════════════════════════════
// 2 · THE PIPELINE
// ═════════════════════════════════════════════════════════════════════════════
emit({
  slug: "pipeline",
  accent: "ops",
  title: "Sutra — The Pipeline",
  h1: "The pipeline — ingest → compile → graph → index",
  subtitle:
    "Four stages, each a script that runs alone, orchestrated by <code>daily.ps1</code>. Every stage reports one of " +
    "<strong>five distinct outcomes</strong> and holds the resource locks it writes. Degradation is allowed; silent " +
    "degradation is not.",
  viewBox: "0 0 1180 640",
  body: [
    group(30, 30, 1120, 250, "ops", "STAGES — each runnable alone, each locked, each reporting five outcomes"),

    box(60, 80, 230, 75, "ops", "1 · ingest", "intake → manifest → extract", "classify + tier, BEFORE anything reads it"),
    box(340, 80, 230, 75, "ops", "2 · compile", "extract → durable page", "NO INPUT CLIP — whole source, or refuse"),
    box(620, 80, 230, 75, "ops", "3 · graph-export", "wikilinks → cytoscape", "anti-regression guard INSIDE the builder"),
    box(895, 80, 225, 75, "ops", "4 · refresh-index", "cross-link + embed", "degrades loudly with no `uv`"),

    box(60, 185, 230, 60, "gate", "locks: raw-inbox, extracts", "acquired in ascending rank"),
    box(340, 185, 230, 60, "gate", "locks: pages", "a loser SKIPS and exits 0"),
    box(620, 185, 230, 60, "gate", "locks: graph-a", "all-or-nothing"),
    box(895, 185, 225, 60, "gate", "locks: embed-index", "per-machine, gitignored"),

    arrow(290, 117, 340, 117, "ops"),
    arrow(570, 117, 620, 117, "ops"),
    arrow(850, 117, 895, 117, "ops"),

    group(30, 320, 545, 210, "derived", "ARTIFACTS — disposable, rebuildable, never a parallel store"),
    box(60, 365, 230, 60, "derived", "raw/manifests/*.md", "tier · hash · extract reason ENUM"),
    box(315, 365, 230, 60, "derived", "compiled/pages/*.md", "source_chars_seen == _total"),
    box(60, 450, 230, 60, "derived", "graph/exports/", "header verified against body"),
    box(315, 450, 230, 60, "derived", "state/index/", "embeddings, tier travels with each vector"),

    group(615, 320, 535, 210, "serve", "WHAT READS THEM"),
    box(645, 365, 220, 60, "serve", "sutra ask", "cited, deterministic-first"),
    box(890, 365, 235, 60, "serve", "sutra-mcp", "14 tools, gated"),
    box(645, 450, 220, 60, "serve", "sutra gate", "the trust demo"),
    box(890, 450, 235, 60, "serve", "sutra doctor", "asserts behaviour, not files"),

    arrow(175, 155, 175, 365, "derived", true),
    arrow(430, 155, 430, 365, "derived", true),
    arrow(735, 155, 735, 365, "derived", true),
    arrow(1005, 155, 1005, 365, "derived", true),

    `<text x="600" y="300" fill="#fbbf24" font-size="9.5" font-weight="600" text-anchor="middle">ok · degraded · failed · skipped(no input) · skipped(policy) — five counters, never one</text>`,

    legend(30, 560, ["ops", "gate", "derived", "serve"]),
  ].join("\n      "),
  cards: [
    card("amber", "Why five outcomes", [
      "Upstream, an LLM failure was caught, counted as a <em>skip</em>, labelled <code>pending/no-extract</code>, and exited <strong>0</strong>.",
      "That one sentence let a <strong>26-day outage look like a quiet week</strong>.",
      "<code>did_work</code> is three-valued — <code>true</code>/<code>false</code>/<code>null</code> = not measurable — so the fix cannot misfire the other way and cry &ldquo;did nothing&rdquo; without proof.",
    ]),
    card("cyan", "No input clip, ever", [
      "One line truncated every source to 6,000 chars. It produced <strong>424 pages that were fluent, correctly formatted, and wrong in specifics</strong>.",
      "Page length was flat across two orders of magnitude of source size, so nothing looked anomalous.",
      "<code>source_chars_seen</code> and <code>_total</code> now make truncation a fact on the artifact.",
    ]),
    card("rose", "Why the locks are ranked", [
      "Three jobs once wrote one artifact with no lock. <code>IgnoreNew</code> guards a task against <em>itself</em>, never against another.",
      "Ascending-rank acquisition makes circular wait impossible <em>by construction</em>.",
      "A global lock was rejected: it would freeze the graph for every long run, and that graph has already been lost once.",
    ]),
  ],
  footer: FOOT("the pipeline"),
});

// ═════════════════════════════════════════════════════════════════════════════
// 3 · ARCHITECTURE + THE LICENCE BOUNDARY
// ═════════════════════════════════════════════════════════════════════════════
emit({
  slug: "architecture",
  accent: "serve",
  title: "Sutra — Architecture",
  h1: "Architecture — and the licence boundary",
  subtitle:
    "Everything outside <code>ee/</code> is Apache-2.0. <code>ee/</code> is commercial. The dependency arrow points " +
    "one way — <strong>Core never imports from ee/</strong> — and CI proves it on every commit by deleting the subtree " +
    "and running the full suite.",
  viewBox: "0 0 1180 690",
  body: [
    group(30, 30, 700, 480, "serve", "CORE — Apache-2.0. `rm -rf ee/` leaves this complete and tested."),

    box(60, 75, 300, 90, "serve", "packages/core", "gate · vault · retrieval · run · audit", "ONE runtime dependency (gray-matter)"),
    box(390, 75, 310, 90, "serve", "packages/mcp", "stdio JSON-RPC · 14 tools", "ZERO dependencies, by design"),

    box(60, 200, 300, 70, "serve", "packages/cli", "--json everywhere", "exit codes are governance signals"),
    box(390, 200, 310, 70, "external", "packages/daemon + dashboard", "OPTIONAL — shape (c) only", "deleting them must break nothing"),

    box(60, 305, 300, 70, "ops", "automation/", "pwsh 7 pipeline + optional Python", "one shared rule set with the core"),
    box(390, 305, 310, 70, "authored", "vault-template/", "the skeleton — ZERO notes"),

    box(60, 410, 640, 70, "external", "plugins/  —  claude-code · hermes · codex", "no absolute path travels; the ceiling is chosen per harness"),

    group(770, 30, 380, 300, "gate", "ee/ — COMMERCIAL. Apache-2.0 does NOT apply."),
    box(800, 75, 320, 60, "gate", "policy/engine + bundle", "E1 · E2 · E5"),
    box(800, 155, 320, 60, "gate", "audit/chain · keys/kms", "E3 · E4"),
    box(800, 235, 320, 60, "gate", "classifier/external · supply/sbom", "E7 · E6"),

    // The one-way dependency arrow, labelled.
    arrow(800, 180, 710, 130, "gate", true, "ee → core"),
    `<rect x="770" y="350" width="380" height="90" rx="8" fill="#0f172a"/>`,
    `<rect x="770" y="350" width="380" height="90" rx="8" fill="rgba(136,19,55,0.25)" stroke="#fb7185" stroke-width="1.5"/>`,
    `<text x="960" y="375" fill="#fb7185" font-size="11" font-weight="700" text-anchor="middle">ee/ CAN ONLY NARROW</text>`,
    `<text x="960" y="395" fill="#e2e8f0" font-size="9.5" text-anchor="middle">tier ≤ min(clearance, surface, purpose)</text>`,
    `<text x="960" y="412" fill="#94a3b8" font-size="9" text-anchor="middle">Asserted over all 162 combinations, every build.</text>`,
    `<text x="960" y="428" fill="#94a3b8" font-size="9" text-anchor="middle">A security review reduces to reading Core's gate.</text>`,

    `<rect x="770" y="460" width="380" height="50" rx="8" fill="#0f172a"/>`,
    `<rect x="770" y="460" width="380" height="50" rx="8" fill="rgba(6,78,59,0.25)" stroke="#34d399" stroke-width="1.5"/>`,
    `<text x="960" y="482" fill="#34d399" font-size="10" font-weight="700" text-anchor="middle">CI, every commit:</text>`,
    `<text x="960" y="499" fill="#e2e8f0" font-size="9.5" text-anchor="middle">rm -rf ee/ &amp;&amp; build &amp;&amp; full test suite</text>`,

    `<text x="380" y="545" fill="#64748b" font-size="9" font-weight="600" text-anchor="middle">THE VAULT IS NOT IN THIS REPO</text>`,
    `<text x="380" y="562" fill="#94a3b8" font-size="9" text-anchor="middle">A user's vault is a separate, user-owned git repo the CLI points at by path.</text>`,
    `<text x="380" y="577" fill="#94a3b8" font-size="9" text-anchor="middle">Deliberately NOT a submodule: a reconcile on a node that runs its own pipeline is a data-loss trap.</text>`,

    legend(30, 610, ["serve", "ops", "authored", "gate", "external"]),
  ].join("\n      "),
  cards: [
    card("emerald", "One dependency", [
      "<code>@sutra/core</code>: one (<code>gray-matter</code>, MIT). <code>@sutra/mcp</code>: zero.",
      "That is the auditability claim expressed as a number — <strong>the thing deciding what your AI can see is readable in an afternoon</strong>.",
      "<code>ee/src/supply/sbom.ts</code> enforces the ceiling, so raising it is a decision rather than an accident.",
    ]),
    card("rose", "Why the boundary is mechanical", [
      "&ldquo;Core depends on <code>ee/</code>&rdquo; discovered at release is expensive; discovered on the commit that introduces it, it is free.",
      "The check stages a copy, deletes <code>ee/</code>, installs, builds, tests — <em>and asserts the build emitted output</em>, because a build that produces nothing and exits 0 looks exactly like one that worked.",
    ]),
    card("slate", "Shape (c) is genuinely optional", [
      "The daemon and dashboard are <strong>separate packages</strong>, not a flag.",
      "A flag would let the dependency creep back one import at a time, until &ldquo;optional&rdquo; was true only in the documentation.",
    ]),
  ],
  footer: FOOT("architecture"),
});

// ═════════════════════════════════════════════════════════════════════════════
// 4 · THE THREE SHAPES
// ═════════════════════════════════════════════════════════════════════════════
emit({
  slug: "shapes",
  accent: "external",
  title: "Sutra — The Three Shapes",
  h1: "Three shapes — the user chooses one",
  subtitle:
    "Each shape is a complete product. <strong>(a) needs no account, no key and no network.</strong> Each later shape " +
    "adds a surface without changing the gate: the ceiling differs, the enforcement does not.",
  viewBox: "0 0 1180 620",
  body: [
    group(30, 30, 350, 430, "serve", "(a) CLI ONLY  —  ~5 min"),
    box(60, 80, 290, 65, "serve", "sutra", "ask · search · gate · capture"),
    box(60, 175, 290, 65, "ops", "automation/", "cron or by hand"),
    box(60, 270, 290, 65, "authored", "your vault", "markdown + git"),
    `<text x="205" y="365" fill="#34d399" font-size="9.5" font-weight="600" text-anchor="middle">zero accounts · zero keys</text>`,
    `<text x="205" y="381" fill="#34d399" font-size="9.5" font-weight="600" text-anchor="middle">zero network</text>`,
    `<text x="205" y="404" fill="#94a3b8" font-size="9" text-anchor="middle">Node ≥20 · git · pwsh 7</text>`,
    `<text x="205" y="428" fill="#94a3b8" font-size="9" text-anchor="middle">Answers are the cited sources</text>`,
    `<text x="205" y="442" fill="#94a3b8" font-size="9" text-anchor="middle">themselves — a real answer.</text>`,

    group(410, 30, 350, 430, "derived", "(b) PLUGIN INTO A HARNESS  ⭐ default  —  +2 min"),
    box(440, 80, 290, 65, "derived", "everything in (a)", "unchanged"),
    box(440, 175, 290, 65, "serve", "sutra-mcp", "14 tools over stdio"),
    box(440, 270, 290, 65, "external", "your harness", "Claude Code · Hermes · Codex"),
    `<text x="585" y="365" fill="#22d3ee" font-size="9.5" font-weight="600" text-anchor="middle">the harness brings the model,</text>`,
    `<text x="585" y="381" fill="#22d3ee" font-size="9.5" font-weight="600" text-anchor="middle">the keys, the chat, the scheduling</text>`,
    `<text x="585" y="404" fill="#94a3b8" font-size="9" text-anchor="middle">We do not build a chat UI, a model</text>`,
    `<text x="585" y="418" fill="#94a3b8" font-size="9" text-anchor="middle">router, or a bot framework. They</text>`,
    `<text x="585" y="432" fill="#94a3b8" font-size="9" text-anchor="middle">already exist, and they are better.</text>`,

    group(790, 30, 360, 430, "gate", "(c) FULL STACK  —  +10–20 min"),
    box(820, 80, 300, 65, "gate", "everything in (b)", "unchanged"),
    box(820, 175, 300, 65, "external", "@sutra/daemon", "loopback by default"),
    box(820, 270, 300, 65, "external", "@sutra/dashboard", "graph · review · reveal"),
    `<text x="970" y="365" fill="#fb7185" font-size="9.5" font-weight="600" text-anchor="middle">a non-loopback bind with no secret</text>`,
    `<text x="970" y="381" fill="#fb7185" font-size="9.5" font-weight="600" text-anchor="middle">and no TLS is REFUSED at startup</text>`,
    `<text x="970" y="404" fill="#94a3b8" font-size="9" text-anchor="middle">The ceiling keys off the BIND HOST,</text>`,
    `<text x="970" y="418" fill="#94a3b8" font-size="9" text-anchor="middle">never the client — an address that</text>`,
    `<text x="970" y="432" fill="#94a3b8" font-size="9" text-anchor="middle">merely looks local grants nothing.</text>`,

    arrow(380, 210, 410, 210, "external", true, "adds"),
    arrow(760, 210, 790, 210, "external", true, "adds"),

    `<rect x="30" y="490" width="1120" height="55" rx="8" fill="#0f172a"/>`,
    `<rect x="30" y="490" width="1120" height="55" rx="8" fill="rgba(6,78,59,0.2)" stroke="#34d399" stroke-width="1.5"/>`,
    `<text x="590" y="513" fill="#34d399" font-size="11" font-weight="700" text-anchor="middle">THE GATE IS IDENTICAL IN ALL THREE</text>`,
    `<text x="590" y="532" fill="#94a3b8" font-size="9.5" text-anchor="middle">Shape (b) on two different harnesses must show byte-identical gate behaviour, differing only by the exposure env var.</text>`,

    legend(30, 570, ["serve", "derived", "gate", "authored", "external"]),
  ].join("\n      "),
  cards: [
    card("emerald", "(a) is a real product", [
      "With no key at all, retrieval, tiering, linking, the graph and <strong>cited answers</strong> work.",
      "A first run that only announces its own limitations is not a product — so the deterministic answer is the <em>floor</em>, not the fallback.",
    ]),
    card("cyan", "(b) is the default", [
      "The harness brings the model, keys, chat, channels and scheduling.",
      "Sutra is the governed substrate they plug into — not a competitor to any of it.",
      "<code>sutra doctor --harness X</code> asserts <strong>14 tools AND a ceiling</strong> by speaking the protocol.",
    ]),
    card("rose", "(c) must be removable", [
      "Release gate 5: uninstalling the daemon and dashboard breaks nothing in (a) or (b).",
      "Enforced by them being separate packages that nothing else imports.",
    ]),
  ],
  footer: FOOT("the three shapes"),
});

// ═════════════════════════════════════════════════════════════════════════════
// 5 · THE MCP TOOL SURFACE
// ═════════════════════════════════════════════════════════════════════════════
const tools = [
  ["sutra_whoami", "identity, gated per file"], ["sutra_search", "keyword · hybrid"],
  ["sutra_semantic_search", "vector recall"], ["sutra_ask", "a cited answer"],
  ["sutra_get_note", "one note in full"], ["sutra_read_section", "one section"],
  ["sutra_list_projects", "active projects"], ["sutra_status", "vault + pipeline health"],
  ["sutra_get_graph", "the hubs"], ["sutra_expand", "one-hop neighbourhood"],
  ["sutra_can_you_see", "THE TRUST DEMO"], ["sutra_list_skills", "public skills only"],
  ["sutra_get_skill", "one skill"],
];
emit({
  slug: "mcp-surface",
  accent: "serve",
  title: "Sutra — The MCP Tool Surface",
  h1: "The MCP surface — 13 reads, 1 write",
  subtitle:
    "Hand-rolled JSON-RPC 2.0 over stdio, <strong>zero external dependencies</strong>, so a user auditing the thing " +
    "that decides what their AI can see reads ~700 lines and nothing else. <strong>No tool accepts a ceiling, tier, " +
    "scope, override or passphrase</strong> — a test walks every published schema on every build.",
  viewBox: "0 0 1180 660",
  body: [
    group(30, 30, 700, 400, "serve", "13 READ TOOLS — every one gated by the same visible()"),
    ...tools.map((t, i) => {
      const col = i % 3, row = Math.floor(i / 3);
      return box(60 + col * 220, 75 + row * 78, 200, 58, i === 10 ? "gate" : "serve", t[0], t[1]);
    }),

    group(770, 30, 380, 190, "gate", "1 WRITE TOOL"),
    box(800, 75, 320, 75, "gate", "sutra_capture", "inbox only · floored to private", "OFF unless SUTRA_MCP_ALLOW_WRITE=1"),
    `<text x="960" y="180" fill="#fb7185" font-size="9" text-anchor="middle">Cannot edit. Cannot overwrite.</text>`,
    `<text x="960" y="195" fill="#fb7185" font-size="9" text-anchor="middle">Cannot create public content.</text>`,
    `<text x="960" y="210" fill="#94a3b8" font-size="9" text-anchor="middle">Fails closed without the opt-in.</text>`,

    `<rect x="770" y="250" width="380" height="180" rx="8" fill="#0f172a"/>`,
    `<rect x="770" y="250" width="380" height="180" rx="8" fill="rgba(136,19,55,0.22)" stroke="#fb7185" stroke-width="1.5"/>`,
    `<text x="960" y="275" fill="#fb7185" font-size="11" font-weight="700" text-anchor="middle">INVARIANT 2</text>`,
    `<text x="960" y="297" fill="#e2e8f0" font-size="9.5" text-anchor="middle">The ceiling is read from the environment</text>`,
    `<text x="960" y="312" fill="#e2e8f0" font-size="9.5" text-anchor="middle">ONCE, at server startup.</text>`,
    `<text x="960" y="336" fill="#94a3b8" font-size="9" text-anchor="middle">It is captured in a readonly field. No</text>`,
    `<text x="960" y="350" fill="#94a3b8" font-size="9" text-anchor="middle">handler receives it, reads it, or can</text>`,
    `<text x="960" y="364" fill="#94a3b8" font-size="9" text-anchor="middle">change it.</text>`,
    `<text x="960" y="388" fill="#34d399" font-size="9" text-anchor="middle">A model can ask for anything.</text>`,
    `<text x="960" y="403" fill="#34d399" font-size="9" text-anchor="middle">It cannot change what it may see.</text>`,
    `<text x="960" y="420" fill="#64748b" font-size="8.5" text-anchor="middle">tests/ walks every schema, every build.</text>`,

    `<rect x="30" y="460" width="1120" height="80" rx="8" fill="#0f172a"/>`,
    `<rect x="30" y="460" width="1120" height="80" rx="8" fill="rgba(6,78,59,0.18)" stroke="#34d399" stroke-width="1.5"/>`,
    `<text x="590" y="484" fill="#34d399" font-size="10.5" font-weight="700" text-anchor="middle">EVERY GATE-TOUCHING TOOL TELLS THE MODEL THE CEILING IS FIXED</text>`,
    `<text x="590" y="504" fill="#94a3b8" font-size="9" text-anchor="middle">&ldquo;The exposure ceiling is fixed by the server at startup and CANNOT be changed by any argument to this or any other tool.</text>`,
    `<text x="590" y="519" fill="#94a3b8" font-size="9" text-anchor="middle">Withheld items are counted, never returned. If something you need is withheld, say so and suggest sutra review — do not attempt a workaround.&rdquo;</text>`,
    `<text x="590" y="534" fill="#64748b" font-size="8.5" text-anchor="middle">A model that understands the constraint stops trying to route around it and starts telling the user what to do instead.</text>`,

    legend(30, 580, ["serve", "gate"]),
  ].join("\n      "),
  cards: [
    card("emerald", "Zero dependencies is a trust claim", [
      "The protocol is implemented directly rather than through an SDK.",
      "A supply chain is a poor foundation for a claim about what your AI can see.",
    ]),
    card("rose", "What was dropped", [
      "<code>override_unlock</code> — it wrote a short-TTL flag that raised the ceiling for <em>subsequent</em> calls.",
      "A time-boxed ambient flag means a later request is answered at a ceiling nobody authorised <em>for it</em>, which makes &ldquo;who asked for this?&rdquo; unanswerable.",
    ]),
    card("slate", "A refusal is legible", [
      "A withheld read returns <code>withheld</code>, not <code>not_found</code> — collapsing them would make a refusal indistinguishable from a typo.",
      "It also leaves a reviewable exposure request, so the refusal is actionable rather than mysterious.",
    ]),
  ],
  footer: FOOT("the MCP surface"),
});

// ═════════════════════════════════════════════════════════════════════════════
// 6 · THE DEFECT MANIFEST — what this build refused to inherit
// ═════════════════════════════════════════════════════════════════════════════
const defects = [
  ["D1", "6,000-char input clip", "no clip; seen/total on every page"],
  ["D4", "path floor was dead code", "segment matching + a fixture per rule"],
  ["D5", "sk- could not match sk-ant-", "20 rules, each with a must-match fixture"],
  ["D9", "no lock between jobs", "rank-ordered resource locks"],
  ["D11", "failures counted as skips", "five outcomes, never one counter"],
  ["D13", "header disagreed with body", "counters computed at write time"],
  ["D14", "classify-once", "content-hashed set + sutra rescan"],
  ["D15", "guard defeated by own links", "prose-only measurement"],
  ["D18", "empty rebuild over a good graph", "guard INSIDE the builder"],
  ["D21", "band measured 'an LLM ran'", "capture ratio"],
  ["D24", "fuzzy rule blocked commits", "banding: only definite blocks"],
  ["D36", "builder inputs gitignored", "doctor asserts inputs are tracked"],
];
emit({
  slug: "inherited-defects",
  accent: "gate",
  title: "Sutra — Inherited Defects",
  h1: "What this build refused to inherit",
  subtitle:
    "Sutra is an <em>extraction</em> from a live system, so by default it inherits every defect that system had — " +
    "including the ones that had been shipping unnoticed for years. Each is closed by a <strong>named test that fails " +
    "against a planted instance</strong>, because a guardrail test that has never been seen to fail is not evidence of " +
    "anything.",
  viewBox: "0 0 1180 700",
  body: [
    group(30, 30, 1120, 500, "gate", "THE MANIFEST — a defect is closed when its test fails against a planted instance"),
    ...defects.map((d, i) => {
      const col = i % 3, row = Math.floor(i / 3);
      const x = 60 + col * 365, y = 75 + row * 108;
      return [
        `<rect x="${x}" y="${y}" width="335" height="88" rx="6" fill="#0f172a"/>`,
        `<rect x="${x}" y="${y}" width="335" height="88" rx="6" fill="rgba(136,19,55,0.28)" stroke="#fb7185" stroke-width="1.5"/>`,
        `<text x="${x + 14}" y="${y + 21}" fill="#fb7185" font-size="11" font-weight="700">${d[0]}</text>`,
        `<text x="${x + 46}" y="${y + 21}" fill="#e2e8f0" font-size="9.5">${d[1]}</text>`,
        `<line x1="${x + 14}" y1="${y + 32}" x2="${x + 321}" y2="${y + 32}" stroke="#fb7185" stroke-width="0.5" opacity="0.4"/>`,
        `<text x="${x + 14}" y="${y + 50}" fill="#34d399" font-size="9" font-weight="600">closed by:</text>`,
        `<text x="${x + 14}" y="${y + 66}" fill="#94a3b8" font-size="9">${d[2]}</text>`,
      ].join("\n      ");
    }),

    `<rect x="30" y="560" width="1120" height="80" rx="8" fill="#0f172a"/>`,
    `<rect x="30" y="560" width="1120" height="80" rx="8" fill="rgba(120,53,15,0.22)" stroke="#fbbf24" stroke-width="1.5"/>`,
    `<text x="590" y="584" fill="#fbbf24" font-size="10.5" font-weight="700" text-anchor="middle">THE RULE THAT PRODUCED ALL OF THESE</text>`,
    `<text x="590" y="605" fill="#e2e8f0" font-size="9.5" text-anchor="middle">Write the test before you believe the fix.</text>`,
    `<text x="590" y="622" fill="#94a3b8" font-size="9" text-anchor="middle">A fix landed once with its invariant written afterwards — and the test immediately FAILED, exposing three further instances the &ldquo;fix&rdquo; had left untouched.</text>`,

    legend(30, 665, ["gate"]),
  ].join("\n      "),
  cards: [
    card("rose", "It happened again during this build", [
      "The positive-coverage test caught <strong>three detection rules</strong> whose fixtures were one character short of their own patterns.",
      "Dead rules — and a rule that matches nothing looks <em>exactly</em> like a rule protecting a clean corpus.",
      "Found before the first commit rather than after a year of shipping.",
    ]),
    card("amber", "Two more, found by running it", [
      "The first cited answer on a fresh install quoted a <strong>template file</strong> full of <code>{{title}}</code> placeholders as a source.",
      "The shipped note templates defaulted to <code>public</code> — a template that mints public notes contradicts the vault's own rule.",
      "Neither would have been found by reading the code.",
    ]),
    card("slate", "And one inside a check", [
      "<code>check-core-alone</code> carried stale build state into its staged copy, so tsc emitted <strong>nothing</strong> and exited 0.",
      "It reported a passing build with no compiled output — D18's exact shape, inside the script written to catch such things.",
      "It now asserts the builder produced output rather than inferring it.",
    ]),
  ],
  footer: FOOT("inherited defects"),
});

// ═════════════════════════════════════════════════════════════════════════════
// The gallery
// ═════════════════════════════════════════════════════════════════════════════
const INDEX = `<!DOCTYPE html>
<!-- SPDX-License-Identifier: Apache-2.0 -->
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sutra — Diagrams</title>
  <link rel="stylesheet" href="assets/tokens.css">
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body { font-family: var(--nc-font-mono); background: var(--nc-bg); color: var(--nc-text); padding: 3rem 2rem; }
    .container { max-width: 1100px; margin: 0 auto; }
    .head { display:flex; align-items:center; gap:1rem; margin-bottom:.75rem; }
    .pulse-dot { width:12px; height:12px; background:#a78bfa; border-radius:50%; animation:pulse 2s infinite; }
    @keyframes pulse { 0%,100%{opacity:1} 50%{opacity:.5} }
    h1 { font-size:1.6rem; letter-spacing:-.025em; }
    .lede { color: var(--nc-text-muted); font-size:.875rem; margin: 0 0 2.5rem 1.75rem; max-width:80ch; line-height:1.7; }
    .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(320px,1fr)); gap:1rem; }
    a.tile { display:block; text-decoration:none; background:var(--nc-surface); border:1px solid var(--nc-border);
             border-radius:var(--nc-radius); padding:1.25rem; transition:all .2s; }
    a.tile:hover { border-color:var(--nc-border-bright); transform:translateY(-2px); }
    .tile h2 { font-size:.9rem; color:var(--nc-text); margin-bottom:.4rem; display:flex; align-items:center; gap:.5rem; }
    .dot { width:8px; height:8px; border-radius:50%; flex-shrink:0; }
    .tile p { font-size:.75rem; color:var(--nc-text-muted); line-height:1.6; }
    .note { margin-top:2.5rem; padding:1.25rem; border:1px solid var(--nc-border); border-radius:var(--nc-radius);
            background:var(--nc-surface); color:var(--nc-text-muted); font-size:.75rem; line-height:1.7; }
    .note strong { color:var(--nc-text); }
    code { color:#a78bfa; }
  </style>
</head>
<body>
  <div class="container">
    <div class="head"><div class="pulse-dot"></div><h1>Sutra — Diagrams</h1></div>
    <p class="lede">Hand-laid inline SVG in self-contained dark HTML. No Mermaid and no client-side layout step,
      so a diagram cannot degrade to a white page or to haphazard routing. Every one renders offline; drag to pan,
      wheel to zoom, hover a box to isolate it.</p>
    <div class="grid">
${built.map((d) => `      <a class="tile" href="${d.slug}.html">
        <h2><span class="dot" style="background:${{ gate: "#fb7185", ops: "#fbbf24", serve: "#34d399", external: "#94a3b8", derived: "#22d3ee", authored: "#a78bfa" }[d.accent]}"></span>${d.h1}</h2>
        <p>${d.subtitle.replace(/<[^>]+>/g, "")}</p>
      </a>`).join("\n")}
    </div>
    <div class="note">
      <strong>Regenerate:</strong> <code>node scripts/diagrams.mjs</code>. The layouts are hand-placed coordinates —
      the part that needs judgement — while the shell, palette and legend are generated, so the set cannot drift apart
      visually. A structural change is not done until its diagram follows.
      <br><br>
      <strong>Offline:</strong> the diagrams render with no network. Only PNG/PDF export needs a CDN, and the buttons
      say so rather than failing mysteriously.
    </div>
  </div>
</body>
</html>
`;
writeFileSync(join(OUT, "index.html"), INDEX, "utf8");
console.log(`  index.html`);
console.log(`\ndiagrams: ${built.length} views + gallery -> docs/diagrams/`);
