#!/usr/bin/env node
// SPDX-License-Identifier: Apache-2.0
/**
 * Generate THIRD-PARTY-NOTICES.md and an SBOM.
 *
 * LICENSING.md §5: "Generate THIRD-PARTY-NOTICES.md automatically. Flag any
 * GPL/AGPL dependency — one of those can force your Core licence, which would
 * undo the choice in §1."
 *
 * The SBOM logic lives in `ee/src/supply/sbom.ts` when the commercial subtree is
 * present. This script is the OPEN-SOURCE path and stands alone, because the
 * Apache-2.0 build must be able to produce its own third-party notices without
 * a commercial component.
 */
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));
const PACKAGES = ["packages/core", "packages/mcp", "packages/cli", "packages/daemon", "packages/dashboard"];

const FORBIDDEN = ["GPL-2.0", "GPL-3.0", "AGPL", "SSPL", "BUSL"];
const REVIEW = ["LGPL", "MPL", "EPL", "CDDL", "UNKNOWN"];

const components = new Map();

for (const pkg of PACKAGES) {
  const manifestPath = join(ROOT, pkg, "package.json");
  if (!existsSync(manifestPath)) continue;
  const manifest = JSON.parse(readFileSync(manifestPath, "utf8"));
  for (const [name, version] of Object.entries(manifest.dependencies ?? {})) {
    if (name.startsWith("@sutra/")) continue;
    const key = `${name}@${version}`;
    if (components.has(key)) {
      components.get(key).introducedBy.push(manifest.name);
      continue;
    }
    let license = "UNKNOWN";
    let repository = "";
    const dep = join(ROOT, "node_modules", name, "package.json");
    if (existsSync(dep)) {
      try {
        const d = JSON.parse(readFileSync(dep, "utf8"));
        license = typeof d.license === "string" ? d.license : (d.license?.type ?? "UNKNOWN");
        repository = typeof d.repository === "string" ? d.repository : (d.repository?.url ?? "");
      } catch {}
    }
    components.set(key, { name, version, license, repository, introducedBy: [manifest.name] });
  }
}

const sorted = [...components.values()].sort((a, b) => a.name.localeCompare(b.name));
const blocked = sorted.filter((c) => FORBIDDEN.some((f) => (c.license ?? "").toUpperCase().includes(f)));
const review = sorted.filter((c) => REVIEW.some((r) => (c.license ?? "").toUpperCase().includes(r)));

const lines = [
  "# Third-party notices",
  "",
  "> Generated by `npm run sbom`. Do not edit by hand.",
  "",
  "Sutra Core is deliberately close to dependency-free. `@sutra/aatma-core` has ONE",
  "runtime dependency and `@sutra/hermes-mcp` has ZERO — the thing deciding what your AI",
  "can see should be readable in an afternoon, and a short list here is part of",
  "that claim rather than a coincidence.",
  "",
  `**${sorted.length} runtime ${sorted.length === 1 ? "dependency" : "dependencies"}.**`,
  "",
  "| Package | Version | Licence | Used by |",
  "|---|---|---|---|",
  ...sorted.map((c) => `| \`${c.name}\` | ${c.version} | ${c.license} | ${c.introducedBy.join(", ")} |`),
  "",
];

if (blocked.length) {
  lines.push(
    "## ⛔ Forbidden licences present",
    "",
    "A copyleft **runtime** dependency can force Core's own licence, which would",
    "silently undo the Apache-2.0 choice. These must be removed:",
    "",
    ...blocked.map((c) => `- \`${c.name}@${c.version}\` — ${c.license}`),
    "",
  );
}
if (review.length) {
  lines.push(
    "## Needs a decision",
    "",
    ...review.map((c) => `- \`${c.name}@${c.version}\` — ${c.license}`),
    "",
  );
}

lines.push(
  "## Vendored assets",
  "",
  "| Asset | Licence | Where |",
  "|---|---|---|",
  "| JetBrains Mono | SIL OFL 1.1 | `assets/fonts/` — the OFL text ships alongside, as the licence requires |",
  "| Inter | SIL OFL 1.1 | `assets/fonts/` |",
  "",
  "Fonts are **vendored, not loaded from a CDN**. An offline install must render",
  "correctly, and a documentation set that phones home to render is one that",
  "stops working in exactly the air-gapped environment it was chosen for.",
  "",
);

writeFileSync(join(ROOT, "THIRD-PARTY-NOTICES.md"), lines.join("\n"), "utf8");
console.log(`sbom: ${sorted.length} runtime dependencies -> THIRD-PARTY-NOTICES.md`);
if (blocked.length) {
  console.error(`sbom: FAIL — ${blocked.length} forbidden licence(s): ${blocked.map((c) => c.name).join(", ")}`);
  process.exit(1);
}
if (review.length) console.warn(`sbom: ${review.length} dependency/dependencies need a licence decision`);
